// source: JobExtendsionService.proto
// Version: 1.0.0

package server

import (
	"context"
	"job-seek/pkg/protos"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// DeleteBookmarkJob implements DeleteBookmarkJob from JobExtendsionServiceServer
// generated by protoc-gen-go-grpc.JobExtendsionServiceServer
func (s JobExtendsionServiceServerImpl) DeleteBookmarkJob(ctx context.Context, req *protos.BookmarkJobRequest) (*protos.BookmarkJobResponse, error) {
	// todo()
	return nil, status.Errorf(codes.Unimplemented, "method  DeleteBookmarkJob  not implemented")
}
