services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    ports:
      - "8654:8654"
    command: 
      - start
      - --log=debug
      - --auth
      - --user=root
      - --pass=root
      - --bind=0.0.0.0:8654 
      - file:/db/database.db
    restart: always
    volumes:
      - ./db:/db
  
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    ports:
      - ${MEILI_PORT:-7700}:7700
    environment:
      - http_proxy
      - https_proxy
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
    restart: unless-stopped
    volumes:
      - ./meilisearch:/data.ms


