services:
  surrealdb:
    image: surrealdb/surrealdb:v1.5.5
    container_name: surrealdb
    ports:
      - "8654:8654"
    user: root
    command:
      - start
      - --log=debug
      - --auth
      - --user=root
      - --pass=root
      - --bind=0.0.0.0:8654 
      - file:/db/database1.db
    restart: always
    volumes:
      - ./db:/db

    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 4G
        reservations:
          cpus: '0.001'
          memory: 1G

  # meilisearch:
  #   image: getmeili/meilisearch:latest
  #   container_name: meilisearch
  #   ports:
  #     - ${MEILI_PORT:-7700}:7700
  #   user: root
  #   environment:
  #     - http_proxy
  #     - https_proxy
  #     - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
  #     - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
  #     - MEILI_ENV=${MEILI_ENV:-development}
  #     - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
  #   restart: unless-stopped
  #   volumes:
  #     - ./meilisearch:/data.ms
