// source: UserManagementService.proto
// Version: 1.0.0

package server

import (
	"context"
	"job-seek/pkg/protos"

	"github.com/twitchtv/twirp"
)

// CreateUserCVProfile implements CreateUserCVProfile from UserManagementServiceServer
// generated by protoc-gen-go-grpc.UserManagementServiceServer
func (s *UserManagementServiceServerImpl) CreateUserCVProfile(ctx context.Context, req *protos.UserCVProfile) (*protos.UserResponse, error) {
	// todo()
	// return nil, status.Errorf(codes.Unimplemented, "method  CreateUserCVProfile  not implemented")
	return nil, twirp.Unimplemented.Errorf("method CreateUserCVProfile not implemented")

}
