// source: UserManagementService.proto
// Version: 1.0.0

package server

import (
	"context"
	"job-seek/pkg/database/model"
	"job-seek/pkg/protos"
	"strconv"

	logrus "github.com/sirupsen/logrus"
	"github.com/twitchtv/twirp"
)

// GetUserProfile implements GetUserProfile from UserManagementServiceServer
// generated by protoc-gen-go-grpc.UserManagementServiceServer
func (s *UserManagementServiceServerImpl) GetUserProfile(ctx context.Context, req *protos.UserProfile) (*protos.UserProfile, error) {
	s.log.WithFields(logrus.Fields{
		"request": req,
	}).Info("GetUserProfile")

	if req.GetUserId() == "" {
		s.log.WithFields(logrus.Fields{
			"req": req,
		}).Error("Failed to fetch user profile, empty fields record id")
		// return nil, status.Errorf(codes.InvalidArgument, "Failed to fetch user profile, empty fields record id")
		return nil, twirp.InvalidArgumentError("UserId", "Failed to fetch user profile, empty fields record id")
	}

	profile, err := s.fetchUserProfile(req.GetUserId())
	if err != nil {
		s.log.WithFields(logrus.Fields{
			"error": err,
		}).Error("Failed to fetch user profile")
		// return nil, status.Errorf(codes.Internal, "Failed to fetch user profile: %v", err)
		return nil, twirp.Internal.Errorf("Failed to fetch user profile: %v", err)
	}
	if profile == nil {
		s.log.WithFields(logrus.Fields{
			"error": err,
		}).Error("Failed to fetch user profile, user not found")
		// return nil, status.Errorf(codes.NotFound, "Failed to fetch user profile: %v", err)
		return nil, twirp.NotFound.Errorf("Failed to fetch user profile: %v", err)
	}

	return profile, nil
	// return nil, status.Errorf(codes.Unimplemented, "method  GetUserProfile  not implemented")
}

func (s *UserManagementServiceServerImpl) fetchUserProfile(recId string) (*protos.UserProfile, error) {
	// You can use a database query or any other method to save the user
	// Return an error if the save operation fails, nil otherwise
	recIdInt, _ := strconv.Atoi(recId)
	instanceModel := &model.UserProfileModel{}
	instanceModel.ID = uint(recIdInt)
	user, err := instanceModel.GetModel(s.dbClient)
	if err != nil {
		s.log.WithFields(logrus.Fields{
			"error": err,
		}).Error("Failed to fetch user profile")
		return nil, err
	}
	return user, nil
}
