// source: UserManagementService.proto
// Version: 1.0.0

package server

import (
	"context"
	"job-seek/pkg/protos"

	"github.com/twitchtv/twirp"
)

// GetUserCVProfile implements GetUserCVProfile from UserManagementServiceServer
// generated by protoc-gen-go-grpc.UserManagementServiceServer
func (s *UserManagementServiceServerImpl) GetUserCVProfile(ctx context.Context, req *protos.GetUserRequest) (*protos.UserCVProfile, error) {
	// todo()
	// return nil, status.Errorf(codes.Unimplemented, "method  GetUserCVProfile  not implemented")
	return nil, twirp.Unauthenticated.Error("method  GetUserCVProfile  not implemented")
}
