// source: UserManagementService.proto
// Version: 1.0.0

package server

import (
	"context"
	"job-seek/pkg/protos"

	"github.com/twitchtv/twirp"
)

// ImportUserProfileFromCV implements ImportUserProfileFromCV from UserManagementServiceServer
// generated by protoc-gen-go-grpc.UserManagementServiceServer
func (s *UserManagementServiceServerImpl) ImportUserProfileFromCV(ctx context.Context, req *protos.UserCVProfile) (*protos.UserResponse, error) {
	// todo()
	// return nil, status.Errorf(codes.Unimplemented, "method ImportUserProfileFromCV not implemented")
	return nil, twirp.Unauthenticated.Error("method ImportUserProfileFromCV not implemented")
}
