// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: job-apply.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobExtendsionService_ApplyJob_FullMethodName          = "/job_seek.job_apply.JobExtendsionService/ApplyJob"
	JobExtendsionService_UpdateJobApply_FullMethodName    = "/job_seek.job_apply.JobExtendsionService/UpdateJobApply"
	JobExtendsionService_ListJobApply_FullMethodName      = "/job_seek.job_apply.JobExtendsionService/ListJobApply"
	JobExtendsionService_GetJobApply_FullMethodName       = "/job_seek.job_apply.JobExtendsionService/GetJobApply"
	JobExtendsionService_JobBookmark_FullMethodName       = "/job_seek.job_apply.JobExtendsionService/JobBookmark"
	JobExtendsionService_ListJobBookmark_FullMethodName   = "/job_seek.job_apply.JobExtendsionService/ListJobBookmark"
	JobExtendsionService_DeleteJobBookmark_FullMethodName = "/job_seek.job_apply.JobExtendsionService/DeleteJobBookmark"
)

// JobExtendsionServiceClient is the client API for JobExtendsionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobExtendsionServiceClient interface {
	// should at least:   job_id and user_id
	ApplyJob(ctx context.Context, in *JobApply, opts ...grpc.CallOption) (*JobResponse, error)
	// should at least:   job_id and user_id
	UpdateJobApply(ctx context.Context, in *JobApply, opts ...grpc.CallOption) (*JobResponse, error)
	// should at least: user_id
	ListJobApply(ctx context.Context, in *GetJobApplyRequest, opts ...grpc.CallOption) (*GetJobApplyResponse, error)
	// should at least: job_id and user_ids
	GetJobApply(ctx context.Context, in *GetJobApplyRequest, opts ...grpc.CallOption) (*JobApply, error)
	// bookmark job
	// should at least:   job_id and user_id
	JobBookmark(ctx context.Context, in *JobBookmarkRequest, opts ...grpc.CallOption) (*JobBookmarkResponse, error)
	// should at least:   user_id
	ListJobBookmark(ctx context.Context, in *JobBookmarkRequest, opts ...grpc.CallOption) (*ListJobBookmarkResponse, error)
	// should at least:   job_id and user_id
	DeleteJobBookmark(ctx context.Context, in *JobBookmarkRequest, opts ...grpc.CallOption) (*JobBookmarkResponse, error)
}

type jobExtendsionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobExtendsionServiceClient(cc grpc.ClientConnInterface) JobExtendsionServiceClient {
	return &jobExtendsionServiceClient{cc}
}

func (c *jobExtendsionServiceClient) ApplyJob(ctx context.Context, in *JobApply, opts ...grpc.CallOption) (*JobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, JobExtendsionService_ApplyJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobExtendsionServiceClient) UpdateJobApply(ctx context.Context, in *JobApply, opts ...grpc.CallOption) (*JobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, JobExtendsionService_UpdateJobApply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobExtendsionServiceClient) ListJobApply(ctx context.Context, in *GetJobApplyRequest, opts ...grpc.CallOption) (*GetJobApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobApplyResponse)
	err := c.cc.Invoke(ctx, JobExtendsionService_ListJobApply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobExtendsionServiceClient) GetJobApply(ctx context.Context, in *GetJobApplyRequest, opts ...grpc.CallOption) (*JobApply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobApply)
	err := c.cc.Invoke(ctx, JobExtendsionService_GetJobApply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobExtendsionServiceClient) JobBookmark(ctx context.Context, in *JobBookmarkRequest, opts ...grpc.CallOption) (*JobBookmarkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobBookmarkResponse)
	err := c.cc.Invoke(ctx, JobExtendsionService_JobBookmark_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobExtendsionServiceClient) ListJobBookmark(ctx context.Context, in *JobBookmarkRequest, opts ...grpc.CallOption) (*ListJobBookmarkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobBookmarkResponse)
	err := c.cc.Invoke(ctx, JobExtendsionService_ListJobBookmark_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobExtendsionServiceClient) DeleteJobBookmark(ctx context.Context, in *JobBookmarkRequest, opts ...grpc.CallOption) (*JobBookmarkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobBookmarkResponse)
	err := c.cc.Invoke(ctx, JobExtendsionService_DeleteJobBookmark_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobExtendsionServiceServer is the server API for JobExtendsionService service.
// All implementations must embed UnimplementedJobExtendsionServiceServer
// for forward compatibility.
type JobExtendsionServiceServer interface {
	// should at least:   job_id and user_id
	ApplyJob(context.Context, *JobApply) (*JobResponse, error)
	// should at least:   job_id and user_id
	UpdateJobApply(context.Context, *JobApply) (*JobResponse, error)
	// should at least: user_id
	ListJobApply(context.Context, *GetJobApplyRequest) (*GetJobApplyResponse, error)
	// should at least: job_id and user_ids
	GetJobApply(context.Context, *GetJobApplyRequest) (*JobApply, error)
	// bookmark job
	// should at least:   job_id and user_id
	JobBookmark(context.Context, *JobBookmarkRequest) (*JobBookmarkResponse, error)
	// should at least:   user_id
	ListJobBookmark(context.Context, *JobBookmarkRequest) (*ListJobBookmarkResponse, error)
	// should at least:   job_id and user_id
	DeleteJobBookmark(context.Context, *JobBookmarkRequest) (*JobBookmarkResponse, error)
	mustEmbedUnimplementedJobExtendsionServiceServer()
}

// UnimplementedJobExtendsionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobExtendsionServiceServer struct{}

func (UnimplementedJobExtendsionServiceServer) ApplyJob(context.Context, *JobApply) (*JobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyJob not implemented")
}
func (UnimplementedJobExtendsionServiceServer) UpdateJobApply(context.Context, *JobApply) (*JobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJobApply not implemented")
}
func (UnimplementedJobExtendsionServiceServer) ListJobApply(context.Context, *GetJobApplyRequest) (*GetJobApplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListJobApply not implemented")
}
func (UnimplementedJobExtendsionServiceServer) GetJobApply(context.Context, *GetJobApplyRequest) (*JobApply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobApply not implemented")
}
func (UnimplementedJobExtendsionServiceServer) JobBookmark(context.Context, *JobBookmarkRequest) (*JobBookmarkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JobBookmark not implemented")
}
func (UnimplementedJobExtendsionServiceServer) ListJobBookmark(context.Context, *JobBookmarkRequest) (*ListJobBookmarkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListJobBookmark not implemented")
}
func (UnimplementedJobExtendsionServiceServer) DeleteJobBookmark(context.Context, *JobBookmarkRequest) (*JobBookmarkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteJobBookmark not implemented")
}
func (UnimplementedJobExtendsionServiceServer) mustEmbedUnimplementedJobExtendsionServiceServer() {}
func (UnimplementedJobExtendsionServiceServer) testEmbeddedByValue()                              {}

// UnsafeJobExtendsionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobExtendsionServiceServer will
// result in compilation errors.
type UnsafeJobExtendsionServiceServer interface {
	mustEmbedUnimplementedJobExtendsionServiceServer()
}

func RegisterJobExtendsionServiceServer(s grpc.ServiceRegistrar, srv JobExtendsionServiceServer) {
	// If the following call pancis, it indicates UnimplementedJobExtendsionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobExtendsionService_ServiceDesc, srv)
}

func _JobExtendsionService_ApplyJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobApply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobExtendsionServiceServer).ApplyJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobExtendsionService_ApplyJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobExtendsionServiceServer).ApplyJob(ctx, req.(*JobApply))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobExtendsionService_UpdateJobApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobApply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobExtendsionServiceServer).UpdateJobApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobExtendsionService_UpdateJobApply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobExtendsionServiceServer).UpdateJobApply(ctx, req.(*JobApply))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobExtendsionService_ListJobApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobExtendsionServiceServer).ListJobApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobExtendsionService_ListJobApply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobExtendsionServiceServer).ListJobApply(ctx, req.(*GetJobApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobExtendsionService_GetJobApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobExtendsionServiceServer).GetJobApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobExtendsionService_GetJobApply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobExtendsionServiceServer).GetJobApply(ctx, req.(*GetJobApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobExtendsionService_JobBookmark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobBookmarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobExtendsionServiceServer).JobBookmark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobExtendsionService_JobBookmark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobExtendsionServiceServer).JobBookmark(ctx, req.(*JobBookmarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobExtendsionService_ListJobBookmark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobBookmarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobExtendsionServiceServer).ListJobBookmark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobExtendsionService_ListJobBookmark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobExtendsionServiceServer).ListJobBookmark(ctx, req.(*JobBookmarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobExtendsionService_DeleteJobBookmark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobBookmarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobExtendsionServiceServer).DeleteJobBookmark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobExtendsionService_DeleteJobBookmark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobExtendsionServiceServer).DeleteJobBookmark(ctx, req.(*JobBookmarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobExtendsionService_ServiceDesc is the grpc.ServiceDesc for JobExtendsionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobExtendsionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "job_seek.job_apply.JobExtendsionService",
	HandlerType: (*JobExtendsionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyJob",
			Handler:    _JobExtendsionService_ApplyJob_Handler,
		},
		{
			MethodName: "UpdateJobApply",
			Handler:    _JobExtendsionService_UpdateJobApply_Handler,
		},
		{
			MethodName: "ListJobApply",
			Handler:    _JobExtendsionService_ListJobApply_Handler,
		},
		{
			MethodName: "GetJobApply",
			Handler:    _JobExtendsionService_GetJobApply_Handler,
		},
		{
			MethodName: "JobBookmark",
			Handler:    _JobExtendsionService_JobBookmark_Handler,
		},
		{
			MethodName: "ListJobBookmark",
			Handler:    _JobExtendsionService_ListJobBookmark_Handler,
		},
		{
			MethodName: "DeleteJobBookmark",
			Handler:    _JobExtendsionService_DeleteJobBookmark_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job-apply.proto",
}
