

[seek_service]
domain = 'https://www.seek.com.au'
cooldown = 2.25
site_key = "AU-Main"
lang_locale = "en-AU"
country_code = "AU"
timezone = "Australia/Sydney"
zone = "anz-1"
max_job_count = 100

[yahoo_search]
domain = 'https://au.search.yahoo.com/'

[surreal_db_service]
host = '192.168.0.102'
port = 8654
user = "job_search_service"
password = "jobseek_job_search"
