// source: JobSearchService.proto
// Version: 1.0.0

package server

import (
	"context"
	"job-seek/pkg/protos"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// GetCompanyDetail implements GetCompanyDetail from JobSearchServiceServer
// generated by protoc-gen-go-grpc.JobSearchServiceServer
func (s JobSearchServiceServerImpl) GetCompanyDetail(ctx context.Context, req *protos.CompanyDetailRequest) (*protos.CompanyDetail, error) {
	// todo()
	return nil, status.Errorf(codes.Unimplemented, "method  GetCompanyDetail  not implemented")
}
