// source: JobSearchService.proto
// Version: 1.0.0

package server

import (
	"context"
	"job-seek/pkg/protos"

	logrus "github.com/sirupsen/logrus"
	"github.com/twitchtv/twirp"
)

// GetJobByPostId implements GetJobByPostId from JobSearchServiceServer
// generated by protoc-gen-go-grpc.JobSearchServiceServer
func (s *JobSearchServiceServerImpl) GetJobByPostId(ctx context.Context, req *protos.JobSearchRequest) (*protos.JobSearchResponse, error) {
	s.mut.TryLock()
	defer s.mut.Unlock()
	s.log.WithFields(logrus.Fields{
		"method": "GetJobByPostId",
		"req":    req,
	}).Info("GetJobByPostId called")
	// todo()
	// return nil, status.Errorf(codes.Unimplemented, "method  GetJobByPostId  not implemented")
	if req.GetPostId() == "" {
		return nil, twirp.InvalidArgumentError("PostId", "cannot be empty")
	}

	jobDetail, err := s.getJobDetail(req.GetPostId())

	if err != nil {
		return nil, twirp.InternalErrorWith(err)
	}

	resp := &protos.JobSearchResponse{}
	resp.Job = append(resp.Job, jobDetail)

	return resp, nil
}
