// Path: job-seek/pkg/database/model/
// code generated by tools/generate_db_model_query/main.go

package model

import (
	"fmt"
	"job-seek/pkg/protos"

	surrealdb "github.com/surrealdb/surrealdb.go"
)

type JobApplyModel struct {
	JobId       string `json:"job_id"`
	UserId      string `json:"user_id"`
	Status      string `json:"status,omitempty"`
	CreatedAt   string `json:"created_at,omitempty"`
	UpdatedAt   string `json:"updated_at,omitempty"`
	CoverLetter string `json:"cover_letter,omitempty"`
	CvContent   string `json:"cv_content,omitempty"`
	CvFile      []byte `json:"cv_file,omitempty"`
	Job         string `json:"job,omitempty"`
	DeletedAt   string `json:"deleted_at,omitempty"`
	Message     string `json:"message,omitempty"`
}

func (m *JobApplyModel) ToProto() protos.JobApply {
	var status = protos.JobStatus(protos.JobStatus_value[m.Status])

	return protos.JobApply{
		JobId:       m.JobId,
		UserId:      m.UserId,
		Status:      &status,
		CreatedAt:   &m.CreatedAt,
		UpdatedAt:   &m.UpdatedAt,
		CoverLetter: &m.CoverLetter,
		CvContent:   &m.CvContent,
		CvFile:      m.CvFile,
		Job:         nil,
		DeletedAt:   &m.DeletedAt,
		Message:     &m.Message,
	}
}

func (m *JobApplyModel) FromProto(p *protos.JobApply) {
	m.JobId = p.JobId
	m.UserId = p.UserId
	m.Status = p.GetStatus().String()
	m.CreatedAt = p.GetCreatedAt()
	m.UpdatedAt = p.GetUpdatedAt()
	m.CoverLetter = p.GetCoverLetter()
	m.CvContent = p.GetCvContent()
	m.CvFile = p.GetCvFile()
	m.Job = p.GetJob().PostId
	m.DeletedAt = p.GetDeletedAt()
	m.Message = p.GetMessage()
}

func (m *JobApplyModel) GetModel(db *surrealdb.DB) (*protos.JobApply, error) {
	result, err := db.Query(`
	SELECT *, (SELECT * FROM Job WHERE PostId = $parent.JobId) AS Job
	FROM JobApply:[$user_id,$job_id];
	`, map[string]interface{}{
		"user_id": m.UserId,
		"job_id":  m.JobId,
	})

	if err != nil {
		return nil, err
	}

	var job *protos.JobApply
	err = surrealdb.Unmarshal(result, job)
	if err != nil {
		return nil, err
	}

	return job, nil

}

func (m *JobApplyModel) CreateModel(sd *surrealdb.DB) error {
	if sd == nil {
		return fmt.Errorf("database connection is nil")
	}
	_, err := sd.Create(fmt.Sprintf("JobApply:[%s,%s]", m.UserId, m.JobId), m)
	return err
}

func (m *JobApplyModel) UpdateModel(sd *surrealdb.DB) error {
	if sd == nil {
		return fmt.Errorf("database connection is nil")
	}
	_, err := sd.Update(fmt.Sprintf("JobApply:[%s,%s]", m.UserId, m.JobId), m)
	return err
}
