// Path: job-seek/pkg/database/model/
// code generated by tools/generate_db_model_query/main.go

package model

import (
	"job-seek/pkg/protos"
)

type PredictedPreferenceMapModel struct {
	UserId string `json:"user_id"`
	MapId  string `json:"map_id"`
}

func (m *PredictedPreferenceMapModel) ToProto() protos.PredictedPreferenceMap {
	return protos.PredictedPreferenceMap{
		UserId: m.UserId,
		MapId:  m.MapId,
	}
}

func (m *PredictedPreferenceMapModel) FromProto(p *protos.PredictedPreferenceMap) {
	m.UserId = p.UserId
	m.MapId = p.MapId
}
