// Path: job-seek/pkg/database/model/
// code generated by tools/generate_db_model_query/main.go

package model

import (
	"fmt"
	"job-seek/pkg/protos"

	surrealdb "github.com/surrealdb/surrealdb.go"
)

type PreferenceKeywordModel struct {
	Id         string `json:"kw_id"`
	UserId     string `json:"user_id"`
	Keyword    string `json:"keyword"`
	Value      string `json:"value"`
	Type       string `json:"type"`
	IsPositive bool   `json:"is_positive"`
}

func (m *PreferenceKeywordModel) ToProto() protos.PreferenceKeyword {
	return protos.PreferenceKeyword{
		KwId:       m.Id,
		UserId:     m.UserId,
		Keyword:    m.Keyword,
		Value:      m.Value,
		Type:       m.Type,
		IsPositive: m.IsPositive,
	}
}

func (m *PreferenceKeywordModel) FromProto(p *protos.PreferenceKeyword) {
	m.Id = p.KwId
	m.UserId = p.UserId
	m.Keyword = p.Keyword
	m.Value = p.Value
	m.Type = p.Type
	m.IsPositive = p.IsPositive
}

func (m *PreferenceKeywordModel) GetModel(db *surrealdb.DB) (*protos.PreferenceKeyword, error) {
	result, err := db.Select(fmt.Sprintf("PreferenceKeyword:%s", m.Id))
	if err != nil {
		return nil, err
	}

	var data *protos.PreferenceKeyword
	err = surrealdb.Unmarshal(result, data)
	if err != nil {
		return nil, err
	}

	return data, nil

}

func (m *PreferenceKeywordModel) CreateModel(sd *surrealdb.DB) error {
	if sd == nil {
		return fmt.Errorf("database connection is nil")
	}

	result, err := sd.Create("PreferenceKeyword", m)
	if err != nil {
		return err
	}
	var data *PreferenceKeywordModel
	err = surrealdb.Unmarshal(result, data)
	if err != nil {
		return err
	}
	m.Id = data.Id
	return nil
}

func (m *PreferenceKeywordModel) UpdateModel(sd *surrealdb.DB) error {
	if sd == nil {
		return fmt.Errorf("database connection is nil")
	}
	_, err := sd.Update(fmt.Sprintf("PreferenceKeyword:%s", m.Id), m)
	return err
}

func (m *PreferenceKeywordModel) DefineModel(sd *surrealdb.DB) error {
	if sd == nil {
		return fmt.Errorf("database connection is nil")
	}
	query := `
DEFINE TABLE IF NOT EXISTS PreferenceKeyword SCHEMAFULL;
-- Field definition
	DEFINE FIELD IF NOT EXISTS	UserId 					ON TABLE PreferenceKeyword TYPE		record<UserAccount>;
	DEFINE FIELD IF NOT EXISTS	Keyword 				ON TABLE PreferenceKeyword TYPE		string;
	DEFINE FIELD IF NOT EXISTS	Value 					ON TABLE PreferenceKeyword TYPE		string;
	DEFINE FIELD IF NOT EXISTS	Type 						ON TABLE PreferenceKeyword TYPE		string;
	DEFINE FIELD IF NOT EXISTS	IsPositive			ON TABLE PreferenceKeyword TYPE		bool;

`
	_, err := sd.Query(query, nil)
	return err
}
