// Path: job-seek/pkg/database/model/
// code generated by tools/generate_db_model_query/main.go

package model

import (
	"fmt"
	"job-seek/pkg/protos"

	"github.com/samber/lo"
	surrealdb "github.com/surrealdb/surrealdb.go"
)

type UserCVProfileModel struct {
	UserId     string   `json:"user_id"`
	CvId       string   `json:"cv_id"`
	CvData     []byte   `json:"cv_data"`
	CvKeywords []string `json:"cv_keywords"`
}

func (m *UserCVProfileModel) ToProto() protos.UserCVProfile {
	return protos.UserCVProfile{
		UserId:     m.UserId,
		CvId:       m.CvId,
		CvData:     m.CvData,
		CvKeywords: []*protos.PreferenceKeyword{},
	}
}

func (m *UserCVProfileModel) FromProto(p *protos.UserCVProfile) {
	m.UserId = p.UserId
	m.CvId = p.CvId
	m.CvData = p.CvData
	m.CvKeywords = lo.Map(p.CvKeywords, func(x *protos.PreferenceKeyword, _ int) string { return x.KwId })
}

func (m *UserCVProfileModel) GetModel(db *surrealdb.DB) (*protos.UserCVProfile, error) {
	result, err := db.Query(`
	SELECT *, (SELECT * FROM PreferenceKeyword WHERE KwId INSIDE $parent.CvKeywords) AS CvKeywords
	FROM UserCVProfile:$cv_id;
	`, map[string]interface{}{
		"cv_id": m.CvId,
	})

	if err != nil {
		return nil, err
	}

	var data *protos.UserCVProfile
	err = surrealdb.Unmarshal(result, data)
	if err != nil {
		return nil, err
	}

	return data, nil

}

func (m *UserCVProfileModel) CreateModel(sd *surrealdb.DB) error {
	if sd == nil {
		return fmt.Errorf("database connection is nil")
	}
	result, err := sd.Query(`
		LET $cv_id = UserCVProfile:uuid();
		INSERT INTO UserCVProfile:$cv_id {
			UserId: $UserId,
			CvId: $cv_id,
			CvData: $CvData,
			CvKeywords: $CvKeywords
		};`, m)
	if err != nil {
		return err
	}
	var data *UserCVProfileModel
	err = surrealdb.Unmarshal(result, data)
	if err != nil {
		return err
	}
	m.CvId = data.CvId
	return nil
}

func (m *UserCVProfileModel) UpdateModel(sd *surrealdb.DB) error {
	if sd == nil {
		return fmt.Errorf("database connection is nil")
	}
	_, err := sd.Update(fmt.Sprintf("UserCVProfile:%s", m.CvId), m)
	return err
}
