// Path: job-seek/pkg/database/model/
// code generated by tools/generate_db_model_query/main.go

package model

import (
	"fmt"
	"job-seek/pkg/protos"

	"github.com/samber/lo"
	surrealdb "github.com/surrealdb/surrealdb.go"
)

type UserSearchPreferenceModel struct {
	RecordId string   `json:"record_id"`
	UserId   string   `json:"user_id"`
	JobId    string   `json:"job_id"`
	Keywords []string `json:"keywords"`
}

func (m *UserSearchPreferenceModel) ToProto() protos.UserSearchPreference {
	return protos.UserSearchPreference{
		RecordId: m.RecordId,
		UserId:   m.UserId,
		JobId:    m.JobId,
		Keywords: []*protos.PreferenceKeyword{},
	}
}

func (m *UserSearchPreferenceModel) FromProto(p *protos.UserSearchPreference) {
	m.RecordId = p.RecordId
	m.UserId = p.UserId
	m.JobId = p.JobId
	m.Keywords = lo.Map(p.Keywords, func(x *protos.PreferenceKeyword, _ int) string { return x.KwId })
}

func (m *UserSearchPreferenceModel) GetModel(db *surrealdb.DB) (*protos.UserSearchPreference, error) {
	result, err := db.Query(
		`
	SELECT *, (SELECT * FROM PreferenceKeyword WHERE KwId INSIDE $parent.Keywords) AS Keywords
	FROM UserSearchPreference:$record_id;
	`, map[string]interface{}{
			"record_id": m.RecordId,
		})

	if err != nil {
		return nil, err
	}

	var data *protos.UserSearchPreference
	err = surrealdb.Unmarshal(result, data)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (m *UserSearchPreferenceModel) CreateModel(sd *surrealdb.DB) error {
	if sd == nil {
		return fmt.Errorf("database connection is nil")
	}

	result, err := sd.Query(`
		LET $record_id = UserSearchPreference:uuid();
		INSERT INTO UserSearchPreference:$record_id {
			RecordId: $record_id,
			UserId: $UserId,
			JobId: $JobId,
			Keywords: $Keywords,
		};
	`, m)
	if err != nil {
		return err
	}
	var data *UserSearchPreferenceModel
	err = surrealdb.Unmarshal(result, data)
	if err != nil {
		return err
	}
	m.RecordId = data.RecordId
	return nil
}

func (m *UserSearchPreferenceModel) UpdateModel(sd *surrealdb.DB) error {
	if sd == nil {
		return fmt.Errorf("database connection is nil")
	}
	_, err := sd.Update(fmt.Sprintf("UserSearchPreference:%s", m.RecordId), m)
	return err
}
